<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="agv_fire_sprinkler">

  <xacro:property name="base_radius" value="0.2"/>
  <xacro:property name="base_length" value="0.15"/>
  <xacro:property name="turret_radius" value="0.15"/>
  <xacro:property name="turret_length" value="0.07"/>
  <xacro:property name="turret_base_radius" value="0.19"/>
  <xacro:property name="turret_base_length" value="0.10"/>
  <xacro:property name="camera_size" value="0.05 0.05 0.05"/>
  <xacro:property name="link1_length" value="0.25"/>
  <xacro:property name="link2_length" value="0.2"/>
  <xacro:property name="x_dim" value="0.7"/>
  <xacro:property name="y_dim" value="0.5"/>
  <xacro:property name="z_dim" value="0.2"/>
  <xacro:property name="robotname" value="agv_fire_sprinkler"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_thickness" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.15"/>
  <xacro:property name= "pi_val" value = "3.14159265359"/>

  <xacro:macro name="inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
    </inertial>
  </xacro:macro>

  <xacro:include filename="$(find my_ddrobot)/model/my_dd_robot.gazebo"/>
 
  <material name="grey">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="green">
    <color rgba="0 0.6 0 1"/>
  </material>
  
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="silver">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="orange">
  <color rgba="1.0 0.647 0.0 1"/>
  </material>

  <material name="cyan">
  <color rgba="0.0 1.0 1.0 1"/>
  </material>


  <link name="base_footprint">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${x_dim} ${y_dim} ${z_dim}"/>
      </geometry>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <box size="${x_dim} ${y_dim} ${z_dim}"/>
      </geometry>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </collision>
    <xacro:inertial mass="2"/>
  </link>
  

  <link name="camera_link">
        <visual>
             <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
    <collision>
        <geometry>
            <box size="0.05 0.05 0.05" />
        </geometry>
    </collision>
    <xacro:inertial mass="0.2"/>
    </link>


    <link name="camera_link_1">
        <visual>
             <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="red"/>
        </visual>
    <collision>
        <geometry>
            <box size="0.05 0.05 0.05" />
        </geometry>
    </collision>
    <xacro:inertial mass="0.2"/>
    </link>


    <link name="camera_link_2">
        <visual>
             <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    <collision>
        <geometry>
            <box size="0.05 0.05 0.05" />
        </geometry>
    </collision>
    <xacro:inertial mass="0.2"/>
    </link>


    <link name="camera_link_3">
        <visual>
             <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
    <collision>
        <geometry>
            <box size="0.05 0.05 0.05" />
        </geometry>
    </collision>
    <xacro:inertial mass="0.2"/>
    </link>


    <link name="camera_link_4">
        <visual>
             <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
    <collision>
        <geometry>
            <box size="0.05 0.05 0.05" />
        </geometry>
    </collision>
    <xacro:inertial mass="0.2"/>
    </link>

  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:inertial mass="${wheel_mass}"/>
  </link>

  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:inertial mass="${wheel_mass}"/>
  </link>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:inertial mass="${wheel_mass}"/>
  </link>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
    </collision>
    <xacro:inertial mass="${wheel_mass}"/>
  </link>

  <joint name="base_rr_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-0.15 -0.275 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="0.4"/>
  </joint>

  <joint name="base_rl_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-0.15 0.275 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="0.4"/>
  </joint>

  <joint name="base_fr_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0.15 -0.275 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="0.4"/>
  </joint>

  <joint name="base_fl_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0.15 0.275 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="1.0" friction="0.4"/>
  </joint>

<link name="nozzle_link">
  <visual>
    <geometry>
      <cylinder length="0.1" radius="0.015"/>
    </geometry>
    <material name="silver"/>
  </visual>
  <collision>
    <geometry>
      <cylinder length="0.1" radius="0.02"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="0.1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
  </inertial>
</link>

<link name="turret_base">
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
  <visual>
    <geometry>
      <cylinder radius="${turret_base_radius}" length="${turret_base_length}"/>
    </geometry>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${turret_base_radius}" length="${turret_base_length}"/>
    </geometry>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </collision>
</link>

<link name="turret">
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
  <visual>
    <geometry>
      <cylinder radius="${turret_radius}" length="${turret_length}"/>
    </geometry>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${turret_radius}" length="${turret_length}"/>
    </geometry>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </collision>
</link>

<link name="arm_link_1">
  <inertial>
    <mass value="0.2"/>
    <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
  </inertial>
  <visual>
    <geometry>
      <box size="0.05 0.05 ${link1_length}"/>
    </geometry>
    <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    <material name="blue"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.05 0.05 ${link1_length}"/>
    </geometry>
    <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
  </collision>

</link>

<link name="arm_link_2">
  <inertial>
    <mass value="0.15"/>
    <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    <inertia ixx="0.008" ixy="0" ixz="0" iyy="0.008" iyz="0" izz="0.008"/>
  </inertial>
  <visual>
    <geometry>
      <box size="0.04 0.04 ${link2_length}"/>
    </geometry>
    <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    <material name="green"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.04 0.04 ${link2_length}"/>
    </geometry>
    <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
  </collision>
</link>

<joint name="base_turret_base_joint" type="fixed">
  <parent link="base_link"/>
  <child link="turret_base"/>
  <origin xyz="0 0 0.15" rpy="0 0 0"/>
</joint>

<joint name="turret_base_turret_joint" type="continuous">
  <parent link="turret_base"/>
  <child link="turret"/>
  <origin xyz="0 0 0.08" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit effort="10" velocity="1.5"/>
  <dynamics damping="0.5" friction="0.2"/>
</joint>

<joint name="arm_link_1_joint" type="revolute">
  <parent link="turret"/>
  <child link="arm_link_1"/>
  <origin xyz="0 0 0.07" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit lower="-1.23" upper="1.23" effort="5" velocity="1.0"/>
  <dynamics damping="0.8" friction="0.5"/>
</joint>

<joint name="arm_link_2_joint" type="revolute">
  <parent link="arm_link_1"/>
  <child link="arm_link_2"/>
  <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit lower="-0.805" upper="0.805" effort="5" velocity="1.0"/>
  <dynamics damping="0.8" friction="0.5"/>
</joint>

<joint name="arm_to_nozzle" type="fixed">
  <parent link="arm_link_2"/>
  <child link="nozzle_link"/>
  <origin xyz="0 0 0.25" rpy="0 0 0"/>
</joint>


<link name="lidar_link">
  <visual>
    <geometry>
      <cylinder radius="0.05" length="0.02"/>
    </geometry>
    <material name="red">
      <color rgba="1 0 0 0.5"/>
    </material>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="0.05" length="0.02"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.2"/>
    <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
  </inertial>
</link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/> 
    <child link="lidar_link"/>
    <origin xyz="0.3 0 0.2101" rpy="0 0 0"/>
  </joint>


  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

      <joint name="arm2_camera_joint" type="fixed">
        <parent link="arm_link_2"/>
        <child link="camera_link"/>
        <origin xyz="-0.045 0 0.15" rpy="0.0 ${-pi_val/2.0} 0.0"/>  
    </joint> 

    <joint name="base_camera_1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link_1"/>
        <origin xyz="0.37 0 0.15" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <joint name="base_camera_2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link_2"/>
        <origin xyz="0.005 0.27 0.15" rpy="${-pi_val/2.0} 0.0 ${pi_val/2.0}"/>
    </joint>

    <joint name="base_camera_3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link_3"/>
        <origin xyz="-0.37 0 0.15" rpy="${-pi_val/2.0} 0.0 ${pi_val}"/>
    </joint>

    <joint name="base_camera_4_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link_4"/>
        <origin xyz="0.005 -0.27 0.15" rpy="${-pi_val/2.0} 0.0 ${-pi_val/2.0}"/>
    </joint>   

    <joint name="camera_optical_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_link_optical"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 ${-pi_val/2.0} 0.0"/>
    </joint>

    <joint name="camera_optical_joint_1" type="fixed">
      <parent link="camera_link_1"/>
      <child link="camera_link_optical_1"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
    </joint>

    <joint name="camera_optical_joint_2" type="fixed">
     <parent link="camera_link_2"/>
     <child link="camera_link_optical_2"/>
      <origin xyz="0.0 0.0 0.0" rpy="${-pi_val/2.0} 0.0 0.0"/>
    </joint> 

  <joint name="camera_optical_joint_3" type="fixed">
  <parent link="camera_link_3"/>
  <child link="camera_link_optical_3"/>
  <origin xyz="0.0 0.0 0.0" rpy="${-pi_val/2.0} 0.0 ${pi_val}"/> 
  </joint>

  <joint name="camera_optical_joint_4" type="fixed">
  <parent link="camera_link_4"/>
  <child link="camera_link_optical_4"/>
  <origin xyz="0.0 0.0 0.0" rpy="${-pi_val/2.0} 0.0 ${-pi_val/2.0}"/> 
  </joint>


  <link name = "camera_link_optical"> </link>
  <link name = "camera_link_optical_1"> </link>
  <link name = "camera_link_optical_2"> </link>
  <link name = "camera_link_optical_3"> </link>
  <link name = "camera_link_optical_4"> </link>

<gazebo>
    <plugin name="arm1_controller" filename="libgazebo_ros_joint_control.so">
      <joint_name>base_arm_link_1_joint</joint_name>
      <control_type>position</control_type>
      <max_force>5</max_force>
      <p_gain>100</p_gain>
      <d_gain>0.1</d_gain>
      <i_gain>0.0</i_gain>
      <target_position>0.0</target_position>
      <command_topic>/arm_link_1_position</command_topic>
    </plugin>
  </gazebo>

<ros2_control name="MyRobotHardware" type="system">
  <hardware>
    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
  </hardware>
  
  <joint name="turret_base_turret_joint">
    <command_interface name="position">
      <param name="min">-3.14</param>
      <param name="max">3.14</param>
    </command_interface>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
  
  <joint name="arm_link_1_joint">
    <command_interface name="position">
      <param name="min">-1.23</param>
      <param name="max">1.23</param>
    </command_interface>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
  
  <joint name="arm_link_2_joint">
    <command_interface name="position">
      <param name="min">-0.805</param>
      <param name="max">0.805</param>
    </command_interface>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
  </joint>
</ros2_control>

<transmission name="turret_transmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="turret_base_turret_joint">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="turret_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="arm1_transmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="arm_link_1_joint">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="arm1_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="arm2_transmission">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="arm_link_2_joint">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
  </joint>
  <actuator name="arm2_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

</robot>