controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster

turret_controller:
  type: position_controllers/JointPositionController

arm1_controller:
  type: position_controllers/JointPositionController

arm2_controller:
  type: position_controllers/JointPositionController